### PR TITLE
Removed unused uuid

### LINKED ISSUE #76: Deprecated unused uuid
You are using a deprecated version of `uuid`. But as I checked everywhere the package is no longer in use. Maybe we can remove it so it won't pop up during `npm install`?

### PR DESCRIPTION
**Pull request by JanKanty**
Closes #76

### CODE REVIEW

**Comment by JanKanty** [comment]
Closes #76

**Comment by JanKanty** [comment]
@Antontelesh so after running `yarn remove uuid` nothing updates in `yarn.lock`. It's probably because earlier today you updated it by dependabot.

**Comment by Antontelesh** [comment]
That’s interesting. Okay, I’ve merged as is

**Pull request merged**
