### PR TITLE
fix(stats): correct pending count in stats

### PR DESCRIPTION
**Pull request by gabrielcaamano-ujet**
Fixes https://github.com/Antontelesh/mochawesome-merge/issues/91

Test data:
[test_data.zip](https://github.com/Antontelesh/mochawesome-merge/files/10189327/test_data.zip)

### CODE REVIEW

**Review by brendt-ujet — APPROVED** [review]
Thank you, looks good.

**Comment by Antontelesh** [comment]
Please, update test fixtures to cover this case

**Comment by gabrielcaamano-ujet** [comment]
@Antontelesh fixtures updated

**Comment by Antontelesh** [comment]
@gabrielcaamano-ujet I merged although deployment failed for some reason. I will take a look later today

**Pull request merged**
