### PR TITLE
Fix duration calculation

### PR DESCRIPTION
**Pull request by basile-parent**
This pull request fixes the duration calculation which had problems ([Issue 61](https://github.com/Antontelesh/mochawesome-merge/issues/61)) and didn't take count of the time loss between each test execution.
The new calculation method just calculate the diff between the start and end (from maxTimeSpan) of the execution.

I also added a comment for better comprehension.

### CODE REVIEW

**Comment by Antontelesh** [comment]
Hi @basile-parent instead of defining dumb values and then overriding them, I would suggest you to pass the result of `getStateTimeSpan` to `generateStats` along with `suites`. This way you'd omit defining dumb values

**Comment by basile-parent** [comment]
Hi @Antontelesh, your comment is relevant. However I think it would be even clearer if all data would be created in the generic `generateStats` function. I will make a new commit. Please let me know if it's good for you.

**Comment by Antontelesh** [comment]
@basile-parent this looks even better! Thank you, I’m merging

**Comment by Antontelesh** [comment]
Oh, a test failed. Would you mind checking it on your side?

**Comment by Antontelesh** [comment]
@basile-parent looks like you need to update snapshots

**Comment by basile-parent** [comment]
@Antontelesh Sorry for the delay, I was pretty busy recently ^^
I updated both json test files (to have a more readable snapshot) and the snapshot. 
Remember to squash the commits (as there are several of them) of my PR.

**Pull request merged**
