### PR TITLE
Add support for output option

### LINKED ISSUE #46: Running with yarn creates invalid json
I'm not sure if this is necessarily a bug, as it works fine with npx - but when running with yarn like so:
`yarn run mochawesome-merge cypress/results/json/*.json > cypress/results/bundle.json`

It will output a file like this:
```
yarn run v1.22.4
$ C:\Users\xxx\xxx\QualityAssurance\node_modules\.bin\mochawesome-merge cypress/results/json/*.json
{
  "stats": {
    "suites": 6,
    "tests": 9,
    "passes": 2,
    "pending": 0,
    "failures": 5,
    "start": "2020-06-02T16:23:27.044Z",
    "end": "2020-06-02T16:23:27.044Z",
    "duration": 150514,
    "testsRegistered": 9,
    "passPercent": 22.22222222222222,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 2,
    "hasSkipped": true
  },
  "results": [
    {
      "uuid": "5c8e828c-65f9-4a1b-ba9e-ccf58bbc09da",
      "title": "",
      "fullFile": "cypress\\integration\\api\\refreshAccessToken.ts",
      "file": "cypress\\integration\\api\\refreshAccessToken.ts",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [],
      "suites": [
        {
          "uuid": "b2978585-4b69-474e-86d1-9f1b8c39543c",
          "title": "Refresh access token endpoint",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
          ...
```

It is invalid because it contains the extra output from yarn in the top of the file - and I know this is because of the piping but maybe the library should support -o flag with a path to where it should output the merged file :)

I might try and file a PR if you think this is something that would be beneficial?

### PR DESCRIPTION
**Pull request by danantal**
- Add yargs
- Add support for output option
- Allow named option for files on top of positional argument in CLI

Fixes #46

### CODE REVIEW

**Comment by danantal** [comment]
Hopefully this is not adding too much :)
This might look a bit overwhelming but it should be pretty straightforward to follow. Please let me know of any changes you require or feel free to modify this PR

**Comment by Antontelesh** [comment]
OMG how profound is that! Thank you for this change, @danantal. I love every piece of this PR, you even kept backwards compatibility. Merging this with pleasure

**Comment by Antontelesh** [comment]
Could you update docs as well to mention the new options?

**Comment by danantal** [comment]
Ah - of course - will make a commit in a few minutes 👍

**Comment by danantal** [comment]
@Antontelesh could you take another look? :)

**Comment by Antontelesh** [comment]
Thanks, let’s try to release this

**Pull request merged**
