### PR TITLE
fix(#17): results array contains false

### PR DESCRIPTION
**Pull request by eltonlauhk01**
#17 
fix the case when the JSON contains
```
  "results": [
    false
  ],
```

### CODE REVIEW

**Comment by Antontelesh** [comment]
Hey @eltonlauhk01, thank you for sending this PR. Did you get why this `false` happens in the first place?

**Comment by eltonlauhk01** [comment]
> Hey @eltonlauhk01, thank you for sending this PR. Did you get why this `false` happens in the first place?

when there's a spec file without any test, or all test are skipped (due to condition) in that spec file.
the mochawesome reporter will still generate the json file
with "results" containing "false"

**Comment by Antontelesh** [comment]
I would than handle this specific case rather than filtering results down the road.

I would like to accept your PR, but please add a sample report to the test data and do the check like this:

```
...(report.results || [])
```

**Comment by eltonlauhk01** [comment]
> I would than handle this specific case rather than filtering results down the road.
> 
> I would like to accept your PR, but please add a sample report to the test data and do the check like this:
> 
> ```
> ...(report.results || [])
> ```
please check the committed test data
`tests/mochawesome-report/mochawesome_003.json`

the `results` array is not null/undefined, so your suggested method might not work as expected

**Comment by Antontelesh** [comment]
@eltonlauhk01 I meant creating another report file mochawesome004.json with results === false

**Comment by Antontelesh** [comment]
Okay, I tried myself. If mochawesome produces an array containing `false` (which is a strange choice), then yes, my proposed solution won't work.

But I would like to
1. Apply filtering inside the `collectReportSuites` function
2. Change it to `.filter(Boolean)`

**Comment by Antontelesh** [comment]
Thank you for such a quick update. I’m going to merge it

**Pull request merged**
